### ISSUE TITLE
type object 'int' has no attribute 'split' error

### ISSUE THREAD

**Issue by Mathiaszero** [kootenpv/cliche#16]
After I installed I went ahead to try the simple script; however, when I ran it, it showed the error in the capture below. How can I resolve this? Thanks in advance.

![image](https://github.com/kootenpv/cliche/assets/55817193/55a80474-fd1b-4875-8cd9-e78f045b2265)

**Comment by kootenpv** [comment]
thanks for posting! I had forgotten to push the new version, after you update, it should work:

`pip install -U cliche`
